export const ENV = {
    API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL!,
    SOCKET_URL: process.env.EXPO_PUBLIC_SOCKET_URL!,
    GOOGLE_EXPO_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID!,
    GOOGLE_ANDROID_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID!,
};
